### ISSUE TITLE
Using prompts from different images

### ISSUE THREAD

**Issue by german36-del** [Hzzone/PseCo#5]
Hi, nice work here! Very glad you share. I was wondering if you have tried or if it is possible to use visual prompts from other images than the prediction one. Thanks!

**Comment by Hzzone** [comment]
Refer to these lines: https://colab.research.google.com/github/Hzzone/PseCo/blob/master/demo_in_the_wild.ipynb#scrollTo=Hl6JioYSULBN

```python
# few-shot
example_boxes = torch.Tensor([[194., 476., 332., 634.],
        [414., 176., 526., 264.],
        [672., 366., 810., 500.]])
example_features = dump_clip_image_features(image, example_boxes).cuda()
```
You can extract CLIP features of your images and then use these features to classify proposals. I am afraid that it would not work well since the model is pre-trained on the few-shot example boxes from the same images. For better performance, you may need to add more example features during training.
